---
- name: "{{ lookup('pipe','date \"+%Y-%m-%d %H-%M-%S\"') }} | Playbook Install Requirement for Spectrum-Scale"
  hosts: spectrumscale
  vars_files:
    - "../vars/vars.yaml"
  gather_facts: false
  tasks:
    - name: "01 - Add EPEL-Release-Repo"
      yum:
        name: epel-release.noarch
        state: present

# Install Software packages
    - name: "02 - Install necassary software programs"
      become: "true"
      yum:
        name:
          - bind-utils.x86_64
          - nfs-utils.x86_64
          - net-tools
          - chrony.x86_64
          - cpp.x86_64
          - gcc.x86_64
          - gcc-c++.x86_64
          - python3
          - elfutils.x86_64
          - elfutils-devel.x86_64
        state: "present"

    - name: "03 - Create Shell-Script"
      template:
        src: "../configs/spectrumscale-install-deploy.sh.j2"
        dest: "{{dir_root}}spectrumscale-install-deploy.sh"
        mode: "0755"
      delegate_to: 127.0.0.1
      tags:
        - retry

    - name: "04 - Check if folder {{ dir_root }} exists"
      stat:
        path: "{{ dir_root }}"
      register: folder_details

    # - name: "04 - DEBUG"
    #   debug:
    #     msg: "{{ folder_details }}"

    - name: "05 - Create Directoy {{ dir_root }}"
      file:
        recurse: "true"
        path: "{{ item }}"
        state: "directory"
      with_items:
        - "{{ dir_root }}"
        - "{{ sps_mountpoint_fs1 }}"
      when:
        - not folder_details.stat.exists
    
    - name: "06 - Spectrum-Scale-Mount-Verzeichnis erstellen"
      file:
        recurse: "true"
        path: "{{ item }}"
        state: "directory"
      with_items:
        - "{{ dest_nas_mount_path }}"

    - name: "07 - Check if {{ dir_root }}{{ sps_install_filename }} exists on Remote-Machine in dir_rootectory"
      stat:
        path: "{{ dir_root }}{{ sps_install_filename }}"
      register: tar_details

    # - name: "07 - DEBUG"
    #   debug:
    #     msg: "{{ tar_details }}"

# Copy sps_install_filename from control-node to managed-nodes
    - name: "08 - Copy {{sps_install_filename}} from control-node to managed-hosts"
      copy:
        src: "{{dir_root}}{{sps_install_filename}}"
        dest: "{{dir_root}}{{sps_install_filename}}"
        mode: "0755"

    - name: "09 - Download Kernel-Devel"
      get_url:
        url: "{{url_kernel_devel}}"
        dest: "{{ dir_root }}/{{kernel_devel}}"


    - name: "10 - Download Kernel-Header"
      get_url:
        url: "{{url_kernel_header}}"
        dest: "{{ dir_root }}/{{kernel_header}}"


    - name: "11 - Install Kernel Devel"
      yum:
        name: "{{ dir_root }}/{{kernel_devel}}"
        allow_downgrade: yes
        state: present
    - name: "12 - Install Kernel Header"
      yum:
        name: "{{ dir_root }}/{{kernel_header}}"
        allow_downgrade: yes
        state: present

# the epel-release must be removed for sps-prerequisites
    - name: "13 - Remove EPEL-Release-Repo"
      yum:
        name: "epel-release.noarch"
        state: "absent"

# Disable firewall for easier setup
    - name: "14 - Stop and disable firewalld"
      service:
        name: firewalld
        state: stopped
        enabled: "false"

# Execute the install-file to install the sps-dependencies
    - name: "15 - Execute SpectrumScale Install-File to extract gpfs-binaries, rpm-files, etc."
      raw: "{{ item }}"
      with_items:
        - "echo '1' | {{ dir_root }}{{ sps_install_filename }}"

# Install GPFS-Packages  
    - name: "18 - Install GPFS-RPM-Packages"
      yum:
        name:
          - "{{gpfs_base}}"
          - "{{gpfs_gskit}}"
          - "{{gpfs_license}}"
          - "{{gpfs_java}}"
          - "{{gpfs_gpl}}"
          - "{{gpfs_docs}}"
          - "{{gpfs_pmsensors}}"
          - "{{gpfs_pmcollector}}"
          - "{{gpfs_msg}}"
          - "{{gpfs_compression}}"
        state: "present"
      tags:
        - rpms

# Install GUI-Packages
    - name: "19 - Install GPFS-RPM-Packages for GUI-Node"
      yum:
        name:
          - "{{gpfs_gui}}"
        state: "present"
      when: "'{{ sps_node3 }}' in inventory_hostname"
      tags:
        - rpms

# Add PATH to bash_profile to execute GPFS-Commands from everywhere
    - name: "20 - Add Path {{gpfs_binary_path}} to bash_profile"
      lineinfile: 
        path: "/root/.bash_profile"
        regexp: "^PATH="
        line: "PATH=$PATH:$HOME/bin:{{gpfs_binary_path}}"
        state: "present"
      tags:
        - bash

# Building the GPFS portability layer on Linux nodes using mmbuildgpl 
    - name: "21 - Build the GPFS-Portability-Layer with mmbuildgpl"
      raw: "{{gpfs_binary_path}}mmbuildgpl"
      tags:
        - gpl


# Disable the rpcbind-service and socket
    - name: "22 - Disable rpcbind-service as prereq from SPS"
      service:
        name: "rpcbind"
        enabled: "false"
        state: "stopped"
      tags:
        - retry

    - name: "23 - Disable rpcbind-socket as prereq from SPS"
      service:
        name: "rpcbind.socket"
        enabled: "false"
        state: "stopped"
      tags:
        - retry

# Create the cluster
    - name: "24 - Create the Cluster with mmcrcluster"
      raw: "{{gpfs_binary_path}}mmcrcluster -N {{sps.sps1.fqdn}}:manager-quorum:{{sps.sps1.hostname}},{{sps.sps2.fqdn}}:manager:{{sps.sps2.hostname}},{{sps.sps3.fqdn}}:manager:{{sps.sps3.hostname}} -C {{sps_cluster_name}}"
      when: "'{{ sps_node1 }}' in inventory_hostname"

# Assign license to Nodes
    - name: "25 - Assign license with mmchlicense"
      raw: "{{gpfs_binary_path}}mmchlicense server --accept -N {{sps.sps1.fqdn}},{{sps.sps2.fqdn}},{{sps.sps3.fqdn}}"
      when: "'{{ sps_node1 }}' in inventory_hostname"
      
# Starten des GPFS-CLusters
    - name: "26 - Start the GPFS-Cluster on all nodes with mmstartup"
      raw: "{{gpfs_binary_path}}mmstartup"

# Create Stanza File from template
    - name: "27 - Create Stanza-File from template"
      template:
        src: "../configs/StanzaFile.j2"
        dest: "{{dir_root}}StanzaFile"
        mode: "0644"
      when: "'{{ sps_node1 }}' in inventory_hostname"

# Create NSDs for Cluster from Stanza File
    - name: "28 - Create NSDs for the Cluster with mmcrnsd"
      raw: "{{gpfs_binary_path}}mmcrnsd -F {{dir_root}}StanzaFile"
      when: "'{{ sps_node1 }}' in inventory_hostname"

# Create Filesystem
    - name: "29 - Create Filesystem for the Cluster with mmcrnsd"
      raw: "{{gpfs_binary_path}}mmcrfs spsopenshift -F {{dir_root}}StanzaFile -A yes -B 2M -j scatter -L 128M -n 2 -S relatime -r 2 -m 2 -T /mnt/spsopenshift -Q yes --filesetdf --perfileset-quota --inode-limit 2M:100K"
      when: "'{{ sps_node1 }}' in inventory_hostname"
      tags:
        - createfs

# Mount Filesystems
    - name: "30 - Mount Filesystems"
      raw: "{{gpfs_binary_path}}mmmount all -N {{sps.sps1.fqdn}},{{sps.sps2.fqdn}},{{sps.sps3.fqdn}}"
      when: "'{{ sps_node1 }}' in inventory_hostname"

# Starten der GUI
    - name: "31 - Start the GPFS-GUI on {{ sps_node3 }}"
      raw: "systemctl start gpfsgui"
      when: "'{{ sps_node3 }}' in inventory_hostname"

# Enable the pmcollector and pmsensor
    - name: "32 - Enable the pmcollectors and pmsensors"
      raw: "{{gpfs_binary_path}}mmperfmon config generate --collectors {{sps.sps1.fqdn}},{{sps.sps2.fqdn}},{{sps.sps3.fqdn}}"
      when: "'{{ sps_node3 }}' in inventory_hostname"


