- name: "{{ lookup('pipe','date \"+%Y-%m-%d %H-%M-%S\"') }} | Playbook - Create Spectrum-Scale-Users"
  hosts: "{{ sps.sps3.fqdn }}"
  gather_facts: false
  vars_files:
    - "../vars/vars.yaml"
  tasks:
    # Stoppe und Starte die GPFSGUI erneut
    - name: "Restarte die GPFSGUI"
      systemd:
        state: restarted
        daemon_reload: yes
        name: gpfsgui
    # Debug-Message
    # - name: "Debug-Message"
    #   debug: msg="{{ cmd_res.stdout }}"
    #   tags:
    #     - debug


    # Warte bis die GUI komplett initialisiert ist
    - name: "Wait until GPFSGUI-Return-Code = 200"
      uri:
        url: "https://scale3"
        follow_redirects: none
        method: GET
        validate_certs: "false"
      register: _result
      until: _result.status == 200
      retries: 120 # 120 * 5 seconds = 10 Minutes 
      delay: 5 # Every 5 seconds


# Lege Benutzer in der Scale-GUI an
    - name: "Create User on GUI-Node"
      raw: "{{ item }}"
      with_items:
        - "/usr/lpp/mmfs/gui/cli/mkuser {{user_security_admin}} -p {{pass_security_admin}} -g SecurityAdmin"
        - "/usr/lpp/mmfs/gui/cli/mkuser {{user_csi_admin}} -p {{pass_csi_admin}} -g CsiAdmin"
        - "/usr/lpp/mmfs/gui/cli/mkuser {{user_cnsa_storage_gui}} -p \'{{pass_cnsa_storage_gui}}\' -g ContainerOperator"
        - "/usr/lpp/mmfs/gui/cli/mkuser {{user_cnss}} -p \'{{pass_cnss}}\' -g ContainerOperator"
      
