- name: "Playbook - Create Spectrum-Scale-Users"
  hosts: "{{ sps_node3 }}"
  gather_facts: false
  vars_files:
    - "./vars/vars.yaml"
  tasks:
    - name: "Create User on GUI-Node"
      raw: "{{ item }}"
      with_items:
        - "/usr/lpp/mmfs/gui/cli/mkuser csiadmin -p Test1234 -g CsiAdmin"
        - "/usr/lpp/mmfs/gui/cli/mkuser patrick -p Test1234 -g SecurityAdmin"
